version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
  - source: /
    destination: /App/Testing/CodeDeploy
file_exists_behavior: OVERWRITE

permissions:
  - object: /App
    pattern: "**"
    owner: root
    group: root
    mode: 777
    type:
      - file

hooks:
  ApplicationStop:
    - location: /App/Testing/CodeDeploy/httpdAppStop.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: httpdAppStart.sh
      timeout: 30
      runas: root
  ValidateService:
    - location: installvalidate.sh
      timeout: 30
      runas: root
