version: 0.2

run-as: root

env:
  shell: bash
  variables:
    filename: "Test"
    Env: "Dev"
    phase: Testing
  git-credential-helper: no
        
phases:
  install:
    run-as: root
    on-failure: CONTINUE
    commands:
      - sudo yum update -y
      - sudo yum install git -y
    finally:
      - echo "Install phase completed, proceed with next phase"
      - echo "Please check the logs for errors"
    
  pre_build:
    run-as: root
    commands:
      - echo "Pre-Build phase starting...."
      - mkdir -p $Env/$phase
      - cd $Env/$phase
      - pwd
      - ls -lrt
      - date
    finally:
      - echo "Pre-Build phase completed, proceed with next phase"
      - echo "Please check the logs for errors"
    
  build:
    run-as: root
    commands:
      - echo "Build phase starting...."
      - touch $filename.txt
    finally:
      - echo "Build phase completed, proceed with next phase"
      - echo "Please check the logs for errors"
    
  post_build:
    run-as: root
    commands:
      - echo "Post-Build phase starting...."
      - chmod -R 777 *
      - pwd
      - ls -lrt
    finally:
      - echo "Post-Build phase completed, proceed with next phase"
      - echo "Please check the logs for errors"
    
artifacts:
  files:
    - '**/*'
